//
//  ZenithiumColorAsset.swift
//  Zenithium
//
//  GENERATED by Scripts/generate-colors.py. Do not edit.
//
//  The catalog and these names come from one table, so a name here cannot refer to a
//  colourset that does not exist — which is the whole reason a string-keyed lookup is
//  acceptable at all. Edit `PALETTE` in the script and run it again.
//

import SwiftUI

/// Every colour in the asset catalog, by name.
enum ZenithiumColorAsset: String, CaseIterable, Sendable {

    /// Blue-leaning near-black. A chosen neutral, not an inherited one.
    case background = "background"

    /// A card's ground.
    case surface = "surface"

    /// A card's ground where it catches light.
    case surfaceElevated = "surfaceElevated"

    /// The visible rule.
    case hairline = "hairline"

    /// The rule between rows inside one card.
    case hairlineSoft = "hairlineSoft"

    /// The spectrum's cold end.
    case spectrumIndigo = "spectrumIndigo"

    /// Anodised violet.
    case spectrumViolet = "spectrumViolet"

    /// Anodised magenta.
    case spectrumMagenta = "spectrumMagenta"

    /// Anodised amber.
    case spectrumAmber = "spectrumAmber"

    /// The spectrum's warm-metal teal.
    case spectrumTeal = "spectrumTeal"

    /// Interaction. The teal end, a little brighter.
    case accent = "accent"

    /// Body and headline text.
    case textPrimary = "textPrimary"

    /// Supporting text.
    case textSecondary = "textSecondary"

    /// Captions and axis labels.
    case textTertiary = "textTertiary"

    /// Mineral green. Cooler than the system's.
    case green = "green"

    /// The middle band.
    case yellow = "yellow"

    /// The low band.
    case red = "red"

    /// Heart-rate zone one's blue-grey.
    case zoneOne = "zoneOne"

    /// Core sleep's slate.
    case coreSleep = "coreSleep"

    /// The colour, resolved against whatever appearance is in force when it is drawn.
    ///
    /// Resolution at draw time is what lets `ZenithiumColor` stay a set of static
    /// properties: a static property has no environment to consult, and a catalog
    /// colour does not need one.
    var color: Color { Color(rawValue, bundle: .main) }
}
