#!/usr/bin/env python3
"""Parse the generated Xcode project the way Xcode does, and refuse what it would refuse.

Why this exists
---------------
`Zenithium.xcodeproj/project.pbxproj` is generated by `Scripts/generate-project.py` and
checked in, so the repository opens without XcodeGen installed. That only helps if the file
Xcode gets is one Xcode can read — and for v0.1 it was not:

    path = AppearancePreference+SwiftUI.swift;

`+` is outside the character set Xcode's plist parser accepts in an unquoted string, so the
whole project opened as "damaged and cannot be opened due to a parse error", with no
indication of which line was at fault. The generator had no quoting function at all; it had
simply never met a file name outside the safe set. XcodeGen quotes correctly, so builds from
`project.yml` were fine and only the checked-in project was broken — which is the least
visible way for this to fail, because nothing in the repository disagreed with itself.

What is checked
---------------
1. The file parses as an OpenStep plist.
2. Every unquoted token is inside Xcode's unquoted-string character set.
3. `rootObject` resolves, and every object reference points at an object that exists.

Exits non-zero and names the line when any of those fails.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PBXPROJ = ROOT / "Zenithium.xcodeproj" / "project.pbxproj"

# The characters Xcode's own plist writer leaves unquoted. Everything else must be quoted.
SAFE = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_$/:.-")

IDENTIFIER = re.compile(r"^[0-9A-F]{24}$")


class ParseError(Exception):
    def __init__(self, message: str, line: int, context: str):
        super().__init__(message)
        self.message = message
        self.line = line
        self.context = context


class Parser:
    """An OpenStep ASCII plist reader that is as strict as Xcode about quoting."""

    def __init__(self, text: str):
        self.text = text
        self.index = 0
        self.unquoted: list[tuple[str, int]] = []

    def fail(self, message: str) -> None:
        line = self.text.count("\n", 0, self.index) + 1
        start = max(0, self.index - 90)
        context = self.text[start:self.index + 90].replace("\n", "\\n")
        raise ParseError(message, line, context)

    def skip(self) -> None:
        while self.index < len(self.text):
            character = self.text[self.index]
            if character in " \t\r\n":
                self.index += 1
            elif self.text.startswith("//", self.index):
                end = self.text.find("\n", self.index)
                self.index = len(self.text) if end < 0 else end + 1
            elif self.text.startswith("/*", self.index):
                end = self.text.find("*/", self.index + 2)
                if end < 0:
                    self.fail("kapanmayan /* yorum")
                self.index = end + 2
            else:
                return

    def value(self):
        self.skip()
        if self.index >= len(self.text):
            self.fail("beklenmeyen dosya sonu")
        character = self.text[self.index]
        if character == "{":
            return self.mapping()
        if character == "(":
            return self.array()
        if character == '"':
            return self.quoted()
        if character == "<":
            end = self.text.find(">", self.index)
            if end < 0:
                self.fail("kapanmayan <veri>")
            self.index = end + 1
            return "<data>"
        return self.bare()

    def mapping(self) -> dict:
        self.index += 1
        result: dict = {}
        while True:
            self.skip()
            if self.index >= len(self.text):
                self.fail("kapanmayan {")
            if self.text[self.index] == "}":
                self.index += 1
                return result
            key = self.value()
            self.skip()
            if self.index >= len(self.text) or self.text[self.index] != "=":
                self.fail(f"{key!r} anahtarından sonra '=' bekleniyordu")
            self.index += 1
            result[key] = self.value()
            self.skip()
            if self.index < len(self.text) and self.text[self.index] == ";":
                self.index += 1
            else:
                self.fail(f"{key!r} değerinden sonra ';' bekleniyordu")

    def array(self) -> list:
        self.index += 1
        result: list = []
        while True:
            self.skip()
            if self.index >= len(self.text):
                self.fail("kapanmayan (")
            if self.text[self.index] == ")":
                self.index += 1
                return result
            result.append(self.value())
            self.skip()
            if self.index < len(self.text) and self.text[self.index] == ",":
                self.index += 1
            elif self.index < len(self.text) and self.text[self.index] == ")":
                self.index += 1
                return result
            else:
                self.fail("dizide ',' ya da ')' bekleniyordu")

    def quoted(self) -> str:
        self.index += 1
        buffer: list[str] = []
        while True:
            if self.index >= len(self.text):
                self.fail("kapanmayan tırnak")
            character = self.text[self.index]
            if character == "\\":
                buffer.append(self.text[self.index + 1:self.index + 2])
                self.index += 2
                continue
            if character == '"':
                self.index += 1
                return "".join(buffer)
            buffer.append(character)
            self.index += 1

    def bare(self) -> str:
        match = re.compile(r"[^\s{}();=,<>\"]+").match(self.text, self.index)
        if match is None:
            self.fail(f"çözümlenemeyen karakter {self.text[self.index]!r}")
        token = match.group(0)
        line = self.text.count("\n", 0, self.index) + 1
        self.unquoted.append((token, line))
        self.index = match.end()
        return token


def check_references(root: dict) -> list[str]:
    """Every object reference has to point at an object that exists."""
    objects = root.get("objects")
    if not isinstance(objects, dict):
        return ["`objects` sözlüğü yok"]

    problems: list[str] = []
    known = set(objects)

    root_object = root.get("rootObject")
    if root_object not in known:
        problems.append(f"rootObject {root_object!r} tanımlı değil")

    def walk(node, owner: str) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                walk(value, owner)
        elif isinstance(node, list):
            for value in node:
                walk(value, owner)
        elif isinstance(node, str) and IDENTIFIER.match(node) and node not in known:
            problems.append(f"{owner} tanımsız nesneye işaret ediyor: {node}")

    for identifier, body in objects.items():
        isa = body.get("isa", "?") if isinstance(body, dict) else "?"
        walk(body, f"{identifier} ({isa})")
    return problems


def main() -> int:
    if not PBXPROJ.exists():
        print(f"HATA: {PBXPROJ} yok", file=sys.stderr)
        return 2

    text = PBXPROJ.read_text(encoding="utf-8")
    parser = Parser(text)
    try:
        root = parser.value()
        parser.skip()
        if parser.index != len(text):
            parser.fail("kök nesneden sonra fazladan içerik")
    except ParseError as error:
        print(f"  ÇÖZÜMLENEMEDİ  satır {error.line}: {error.message}")
        print(f"                 ...{error.context}...")
        print("\nXcode bu dosyayı 'damaged' diye reddeder.", file=sys.stderr)
        return 1

    failures = 0
    for token, line in parser.unquoted:
        offending = sorted(set(token) - SAFE)
        if offending:
            failures += 1
            print(
                f"  TIRNAKSIZ  satır {line}: {token!r} — "
                f"Xcode'un çözemeyeceği karakter: {', '.join(repr(c) for c in offending)}"
            )

    for problem in check_references(root):
        failures += 1
        print(f"  BAĞLANTI   {problem}")

    if failures:
        print(
            "\nBUILD-1 project.yml'i yetkili sayıyor: farkı orada değil, üreteçte kapat.",
            file=sys.stderr,
        )
        return 1

    objects = root.get("objects", {})
    print(f"OK    project.pbxproj çözümlendi — {len(objects)} nesne, "
          f"{len(parser.unquoted)} tırnaksız simge, hepsi Xcode'un kabul ettiği kümede")
    return 0


if __name__ == "__main__":
    sys.exit(main())
