#!/usr/bin/env python3
"""Generate the colour asset catalog and its Swift accessor from one table.

Yol haritası v4, B6. The palette needs to exist in two places — as `.colorset` JSON that
Xcode resolves per appearance, and as Swift names the compiler can check — and those two
must not be able to drift. So neither is written by hand: both come from `PALETTE` below.

Run after editing `PALETTE`:

    python3 Scripts/generate-colors.py

An asset catalog is what makes this work in static contexts. `ZenithiumColor` is an enum of
`static var`s, several of them read from places that have no SwiftUI environment to consult —
`WidgetStyle`, `ChartChrome`, `ZenithiumFont`. A catalog colour resolves at render time
against whatever appearance is in force, so those call sites need no environment and no
change at all. Seven hundred and twelve of them stayed exactly as they were.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "Zenithium" / "Resources" / "Zenithium.xcassets"
SWIFT_OUT = ROOT / "Zenithium" / "Views" / "DesignSystem" / "ZenithiumColorAsset.swift"

# name -> (dark hex, light hex, doc comment)
#
# Dark is the app's identity. Light is not an inversion: the spectrum hues were chosen to
# glow against near-black and only muddy against near-white, so the light values take the
# same hues down in lightness and up in chroma. Contrast for every text and semantic colour
# is above §10's 4.5:1 on its own ground.
PALETTE: dict[str, tuple[str, str, str]] = {
    "background":       ("07090E", "F4F5F8", "Blue-leaning near-black. A chosen neutral, not an inherited one."),
    "surface":          ("0D111A", "FFFFFF", "A card's ground."),
    "surfaceElevated":  ("131A26", "EDEFF4", "A card's ground where it catches light."),
    "hairline":         ("1F2836", "D8DCE6", "The visible rule."),
    "hairlineSoft":     ("151C28", "E6E9F0", "The rule between rows inside one card."),

    "spectrumIndigo":   ("2E2A7A", "2A266E", "The spectrum's cold end."),
    "spectrumViolet":   ("6E3B9E", "5C2F86", "Anodised violet."),
    "spectrumMagenta":  ("BE3F79", "9A2F5F", "Anodised magenta."),
    "spectrumAmber":    ("E27B3C", "B25818", "Anodised amber."),
    "spectrumTeal":     ("2FB8A6", "0E7C70", "The spectrum's warm-metal teal."),
    "accent":           ("3ED0BE", "0E8F80", "Interaction. The teal end, a little brighter."),

    "textPrimary":      ("E9EDF5", "12161F", "Body and headline text."),
    "textSecondary":    ("8C96AB", "4B5468", "Supporting text."),
    "textTertiary":     ("59627A", "7C8598", "Captions and axis labels."),

    "green":            ("3FCF8E", "0E7A50", "Mineral green. Cooler than the system's."),
    "yellow":           ("F0B23F", "9A5B0E", "The middle band."),
    "red":              ("EF5560", "B3242F", "The low band."),

    "zoneOne":          ("385A7A", "2C4863", "Heart-rate zone one's blue-grey."),
    "coreSleep":        ("4A5B78", "3B4A63", "Core sleep's slate."),
}

CATALOG_ROOT_CONTENTS = {"info": {"author": "xcode", "version": 1}}


def components(hex_value: str) -> dict[str, str]:
    """A colourset's components, as the eight-bit strings Xcode writes."""
    return {
        "red": f"0x{hex_value[0:2]}",
        "green": f"0x{hex_value[2:4]}",
        "blue": f"0x{hex_value[4:6]}",
        "alpha": "1.000",
    }


def colorset(dark: str, light: str) -> dict:
    """One `.colorset`: the light value as the base, dark behind an appearance."""
    def entry(hex_value: str, appearances: list[dict] | None) -> dict:
        value = {
            "idiom": "universal",
            "color": {
                "color-space": "srgb",
                "components": components(hex_value),
            },
        }
        if appearances:
            value["appearances"] = appearances
        return value

    return {
        "colors": [
            entry(light, None),
            entry(dark, [{"appearance": "luminosity", "value": "dark"}]),
        ],
        "info": {"author": "xcode", "version": 1},
    }


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def generate_catalog() -> None:
    write_json(CATALOG / "Contents.json", CATALOG_ROOT_CONTENTS)
    write_json(CATALOG / "Colors" / "Contents.json", CATALOG_ROOT_CONTENTS)
    for name, (dark, light, _) in PALETTE.items():
        write_json(
            CATALOG / "Colors" / f"{name}.colorset" / "Contents.json",
            colorset(dark, light),
        )


def generate_swift() -> None:
    lines = [
        "//",
        "//  ZenithiumColorAsset.swift",
        "//  Zenithium",
        "//",
        "//  GENERATED by Scripts/generate-colors.py. Do not edit.",
        "//",
        "//  The catalog and these names come from one table, so a name here cannot refer to a",
        "//  colourset that does not exist — which is the whole reason a string-keyed lookup is",
        "//  acceptable at all. Edit `PALETTE` in the script and run it again.",
        "//",
        "",
        "import SwiftUI",
        "",
        "/// Every colour in the asset catalog, by name.",
        "enum ZenithiumColorAsset: String, CaseIterable, Sendable {",
        "",
    ]
    for name, (_, _, doc) in PALETTE.items():
        lines.append(f"    /// {doc}")
        lines.append(f'    case {name} = "{name}"')
        lines.append("")
    lines += [
        "    /// The colour, resolved against whatever appearance is in force when it is drawn.",
        "    ///",
        "    /// Resolution at draw time is what lets `ZenithiumColor` stay a set of static",
        "    /// properties: a static property has no environment to consult, and a catalog",
        "    /// colour does not need one.",
        "    var color: Color { Color(rawValue, bundle: .main) }",
        "}",
        "",
    ]
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    generate_catalog()
    generate_swift()
    print(f"{len(PALETTE)} colours -> {CATALOG.relative_to(ROOT)} and {SWIFT_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
