#!/usr/bin/env python3
"""Embed the authoritative constants for offline inspection, without a second hand-written table."""
from pathlib import Path
root = Path(__file__).resolve().parent.parent
source = (root / 'Zenithium/Engines/EngineConstants.swift').read_text()
output = root / 'Zenithium/ViewModels/EngineReferenceContent.swift'
text = '// Generated by Scripts/generate-reference-content.py.\nimport Foundation\n\nenum EngineReferenceContent {\n    static let constants = #"""\n' + source + '\n"""#\n}\n'
if not output.exists() or output.read_text() != text:
    output.write_text(text)
print('Hesap sabitleri uygulama içi kaynakla eşitlendi.')
